version: '3'
services:
    php:
        container_name: simpson-quotes-php
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./src/:/var/www/
        networks:
            - sq-network
    nginx:
        container_name: simpson-quotes-nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./src/:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - sq-network
    mysql:
        container_name: simpson-quotes-mysql
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: simpsons
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./src/dbdata:/var/lib/mysql
        networks:
            - sq-network
networks:
    sq-network:
        driver: bridge
volumes:
    dbdata:
        driver: local